version: 2
jobs:
  build:
    working_directory: app/src/androidTest/java/com/mytaxi/android_demo/MultiActivityTest.java
    docker:
      - image: debian:stretch
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - run:
      name: Chmod permissions 
       command: sudo chmod +x ./gradlew androidDependencies
   #   - run:
    #      name: Download Dependencies
    #      command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
