version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: debian:stretch
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Run Tests
        
      - store_artifacts:
          path: app/build/reports
         
      - store_test_results:
          path: app/build/test-results
     
     
version: 2
jobs:
          
          test:
  override:
    # start the emulator
    - emulator -avd circleci-android22 -no-audio -no-window:
        background: true
        parallel: true
    # wait for it to have booted
    - circle-android wait-for-boot
    # unlock the emulator screen
    - sleep 30
    - adb shell input keyevent 82
    # run tests  against the emulator.
    - ./gradlew connectedAndroidTest -PdisablePreDex
    # copy the build outputs to artifacts
    - cp -r app/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
    - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS
